# Copyright (c) 2017-2019, Lawrence Livermore National Security, LLC. 
#
# Produced at the Lawrence Livermore National Laboratory 
#
# LLNL-CODE-738041.
#
# All rights reserved. 
#
# This file is part of Shroud.
#
# For details about use and distribution, please read LICENSE.
#
########################################################################
dist: trusty
sudo: false

language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

# Command to install dependencies.
# This installs Shroud into the virtualenv.
install:
   - python setup.py install
#  - pip install -r requirements.txt

# Command to run tests.
script:
  # echo make version
  - make --version
  - make PYTHONEXE=python test
  - make PYTHONEXE=python do-test

notifications:
  email:
    recipients:
      - taylor16@llnl.gov
    on_success: always
    on_failure: always
